services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: N8N_HOST
        value: automacoes.worksimple.online
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://automacoes.worksimple.online
